# Generated by Django 5.1.7 on 2025-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('anons', models.CharField(max_length=50, verbose_name='anons')),
                ('full_text', models.TextField(verbose_name='full text')),
                ('date', models.CharField(max_length=50, verbose_name='publish date')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
