# Generated by Django 5.1.7 on 2025-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='reviews_amount',
            field=models.IntegerField(default=0, verbose_name='reviews_amount'),
        ),
    ]
