# Generated by Django 5.1.7 on 2025-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_teacher_reviews_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('lessons_amount', models.IntegerField(verbose_name='lessons_amount')),
                ('courses_amount', models.IntegerField(verbose_name='courses_amount')),
                ('reviews_amount', models.IntegerField(default=0, verbose_name='reviews_amount')),
                ('average', models.FloatField(verbose_name='average')),
            ],
        ),
    ]
