# Generated by Django 5.1.7 on 2025-03-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='average',
            field=models.FloatField(default=0, verbose_name='average'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses_amount',
            field=models.IntegerField(default=0, verbose_name='courses_amount'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lessons_amount',
            field=models.IntegerField(default=0, verbose_name='lessons_amount'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='total',
            field=models.FloatField(default=0, verbose_name='total'),
        ),
    ]
